
// <auto-generated/>

namespace Nez
{
	class Content
	{
		public static class Font
		{
			public const string scoreFont = @"Font\scoreFont";
		}

		public static class Letters
		{
			public const string letterA = @"Letters\letterA";
			public const string letterB = @"Letters\letterB";
			public const string letterC = @"Letters\letterC";
			public const string letterD = @"Letters\letterD";
			public const string letterE = @"Letters\letterE";
			public const string letterF = @"Letters\letterF";
			public const string letterG = @"Letters\letterG";
			public const string letterH = @"Letters\letterH";
			public const string letterI = @"Letters\letterI";
			public const string letterJ = @"Letters\letterJ";
			public const string letterK = @"Letters\letterK";
			public const string letterL = @"Letters\letterL";
			public const string letterM = @"Letters\letterM";
			public const string letterN = @"Letters\letterN";
			public const string letterO = @"Letters\letterO";
			public const string letterP = @"Letters\letterP";
			public const string letterQ = @"Letters\letterQ";
			public const string letterR = @"Letters\letterR";
			public const string letterS = @"Letters\letterS";
			public const string letterT = @"Letters\letterT";
			public const string letterU = @"Letters\letterU";
			public const string letterV = @"Letters\letterV";
			public const string letterW = @"Letters\letterW";
			public const string letterX = @"Letters\letterX";
			public const string letterY = @"Letters\letterY";
			public const string letterZ = @"Letters\letterZ";
		}

		public static class Numbers
		{
			public const string number0 = @"Numbers\number0";
			public const string number1 = @"Numbers\number1";
			public const string number2 = @"Numbers\number2";
			public const string number3 = @"Numbers\number3";
			public const string number4 = @"Numbers\number4";
			public const string number5 = @"Numbers\number5";
			public const string number6 = @"Numbers\number6";
			public const string number7 = @"Numbers\number7";
			public const string number8 = @"Numbers\number8";
			public const string number9 = @"Numbers\number9";
		}

		public static class Planes
		{
			public const string planeBlue1 = @"Planes\planeBlue1";
			public const string planeBlue2 = @"Planes\planeBlue2";
			public const string planeBlue3 = @"Planes\planeBlue3";
			public const string planeGreen1 = @"Planes\planeGreen1";
			public const string planeGreen2 = @"Planes\planeGreen2";
			public const string planeGreen3 = @"Planes\planeGreen3";
			public const string planeRed1 = @"Planes\planeRed1";
			public const string planeRed2 = @"Planes\planeRed2";
			public const string planeRed3 = @"Planes\planeRed3";
			public const string planeYellow1 = @"Planes\planeYellow1";
			public const string planeYellow2 = @"Planes\planeYellow2";
			public const string planeYellow3 = @"Planes\planeYellow3";
		}

		public static class Terrain
		{
			public const string background = @"Terrain\background";
			public const string groundDirt = @"Terrain\groundDirt";
			public const string groundGrass = @"Terrain\groundGrass";
			public const string groundIce = @"Terrain\groundIce";
			public const string groundRock = @"Terrain\groundRock";
			public const string groundSnow = @"Terrain\groundSnow";
			public const string puffLarge = @"Terrain\puffLarge";
			public const string puffSmall = @"Terrain\puffSmall";
			public const string rock = @"Terrain\rock";
			public const string rockDown = @"Terrain\rockDown";
			public const string rockGrass = @"Terrain\rockGrass";
			public const string rockGrassDown = @"Terrain\rockGrassDown";
			public const string rockIce = @"Terrain\rockIce";
			public const string rockIceDown = @"Terrain\rockIceDown";
			public const string rockSnow = @"Terrain\rockSnow";
			public const string rockSnowDown = @"Terrain\rockSnowDown";
		}

		public static class UI
		{
			public const string buttonLarge = @"UI\buttonLarge";
			public const string buttonSmall = @"UI\buttonSmall";
			public const string medalBronze = @"UI\medalBronze";
			public const string medalGold = @"UI\medalGold";
			public const string medalSilver = @"UI\medalSilver";
			public const string starBronze = @"UI\starBronze";
			public const string starGold = @"UI\starGold";
			public const string starSilver = @"UI\starSilver";
			public const string tap = @"UI\tap";
			public const string tapLeft = @"UI\tapLeft";
			public const string tapRight = @"UI\tapRight";
			public const string tapTick = @"UI\tapTick";
			public const string textGameOver = @"UI\textGameOver";
			public const string textGetReady = @"UI\textGetReady";
			public const string uIbg = @"UI\UIbg";
		}


	}
}



